# SITE CONFIGURATION
baseurl: ""
url: "https://lucassouto.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Lucas Souto - Blog"
  avatar: 
  favicon: "assets/favicon.ico" 
  gravatar: # Email MD5 hash
  description: "Meu blog pessoal para falar de tecnologia e outras coisas legais"

  # Header and footer text
  header_text: >
     <p>Meu blog pessoal para falar de tecnologia e outras coisas legais</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: false  # Make sure you created a feed.xml with feed.xml layout
  email_address: "lucasinfologos@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "lucassouto"
  google_plus:
  instagram:
  keybase:
  linkedin: "https://www.linkedin.com/in/lucas-souto-184186129/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  twitter: "@lucassouto_1000"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "lucassouto-github-io"
  katex: true # Enable if using math markup
  portfolio: false
  search: true
  tags: true
  
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
